require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.packer_compiled"

--[[ Lazy Loading Plugins
require "user.lsp"
require "user.cmp"
require "user.treesitter"
require "user.colorscheme"
require "user.lualine"
require "user.bufferline"
require "user.telescope"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.toggleterm"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.surround"
require "user.project"
require "user.flutter"
-- -- End ]]
